Componente AudioSource
El-limon-mecanico/Quack-Engine pull request #40
Opened 2021-05-19 17:15 UTC by jorgmo02

Para que una entidad tenga sonido debería bastar con añadir este componente e indicar la ruta en la que está el sonido (por ejemplo, "singing.wav").
También he hecho un poco de manejo de excepciones a la hora de leer un componente, que petaba a veces. Ahora el juego se queda como sin hacer nada.

2021-05-19 19:38 UTC, Agusmoure commented on QuackEngineSol/Src/QuackEngine/AudioSource.cpp
> +	channel = mngr_->createSound(source, source);
Aqui pon que la ID se lea desde lua no se la iguales al source xfi

2021-05-20 17:51 UTC, JuanmaSalva approved these changes

2021-05-20 18:31 UTC, tatiandu requested changes

2021-05-20 18:31 UTC, tatiandu commented on QuackEngineSol/Src/QuackEngine/AudioSource.cpp
> +void AudioSource::setVolume(float value) {
No funciona

2021-05-22 19:49 UTC, tatiandu approved these changes
Ya funciona

2021-05-22 19:50 UTC, merged